### ISSUE TITLE
4.0.1版本启动失败

### ISSUE THREAD

**Issue by Malayke** [Qrilee/CharlesLoader#1]
系统：macOS 10.12.2
Java：1.8.0_111

→ java -javaagent:CharlesLoader.jar -jar charles.jar
objc[4630]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java (0x10af334c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10c7ef4e0). One of the two will be used. Which one is undefined.
=========启动动态loader========
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: com.xk72.charles.macos.c cannot be cast to com.xk72.charles.macos.gui.a
	at com.xk72.charles.gui.CharlesFrame.<init>(Unknown Source)
	at com.xk72.charles.gui.S.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Qrilee** [comment]
了解，春节后修复下

**Comment by Malayke** [comment]
坐等大侠修复

**Comment by Qrilee** [comment]
mac 版本吗

**Comment by Malayke** [comment]
不好意思，没注意看，才看到回复。
是的，macOS版本的！🙏🏻

**Comment by Qrilee** [comment]
链接: https://pan.baidu.com/s/1i5xFboT 密码: 5uiu

**Comment by Malayke** [comment]
谢大牛，可用
